// adding-a-react-18-user-interface-to-identityserver-6/IdentityServer.Ui/src/pages/Login.tsx
﻿import React, { FormEvent, useCallback } from "react";
import { useSearchParams } from "react-router-dom";

export default function Login() {
  const [searchParams] = useSearchParams();

  const handleSubmit = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault();

      const form = event.currentTarget;

      const formData = new FormData(form);

      const response = await fetch("/api/login", {
        body: JSON.stringify({
          userName: formData.get("userName"),
          password: formData.get("password"),
          returnUrl: searchParams.get("returnUrl"),
        }),
        headers: {
          "Content-Type": "application/json",
        },
        method: "POST",
      });

      if (response.ok) {
        const { returnUrl } = await response.json();

        window.location.href = returnUrl;
      } else {
        form.reset();
      }
    },
    [searchParams],
  );

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label htmlFor="userName">Username: </label>
        <input
          autoComplete="username"
          id="userName"
          name="userName"
          required
          type="text"
        />
      </div>

      <div>
        <label htmlFor="password">Password: </label>
        <input
          autoComplete="current-password"
          id="password"
          name="password"
          required
          type="password"
        />
      </div>

      <button type="submit">Log in</button>
    </form>
  );
}

// adding-an-angular-14-user-interface-to-identityserver-6/IdentityServer/ClientApp/src/app/account/login/login.component.ts
﻿import {HttpClient} from "@angular/common/http";
import {Component} from '@angular/core';
import {FormBuilder, Validators} from "@angular/forms";
import {ActivatedRoute} from "@angular/router";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  loginForm = this.formBuilder.group({
    userName: ['', Validators.required],
    password: ['', Validators.required],
    returnUrl: [this.route.snapshot.queryParamMap.get('returnUrl')]
  });

  constructor(private formBuilder: FormBuilder, private http: HttpClient, private route: ActivatedRoute) {}

  onSubmit() {
    this.http.post<{ returnUrl: string }>('/api/login', this.loginForm.value).subscribe({
      next: ({returnUrl}) => {
        window.location.href = returnUrl;
      },
      error: () => {
        this.loginForm.reset();
      }
    })
  }
}

﻿<form (ngSubmit)="onSubmit()" [formGroup]="loginForm">
  <div>
    <label for="userName">Username: </label>
    <input autocomplete="username" formControlName="userName" id="userName" required type="text">
  </div>

  <div>
    <label for="password">Password: </label>
    <input autocomplete="current-password" formControlName="password" id="password" required type="password">
  </div>

  <button [disabled]="loginForm.invalid" type="submit">Login</button>
</form>
